on: [push]
jobs:
  extract:
    runs-on: ubuntu-latest
    name: 'Extracts and prepares Freelex data for use by native applications'
    steps:
      - uses: actions/checkout@v2
      - run: make build update_assets
      - run: tar -cf assets.tar.gz assets
  release:
    runs-on: ubuntu-latest
    name: "Create release using extracted Freelex data"
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Quarterly release of NZSL Dictionary data
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./assets.tar.gz
          asset_name: assets.tar.gz
          asset_content_type: application/gzip
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nzsl.db
          asset_name: nzsl.db
          asset_content_type: application/vnd.sqlite3
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nzsl.dat
          asset_name: nzsl.dat
          asset_content_type: text/plain
